#!/bin/bash

# set environment variables on GitHub Actions CI

set -e -x

echo "SME_DEPS_COMMON_VERSION: ${SME_DEPS_COMMON_VERSION}"
echo "PATH: $PATH"
echo "MSYSTEM: $MSYSTEM"

# temporary workaround for cmake 4.0 complaining about symengine min cmake version being too low:
export CMAKE_POLICY_VERSION_MINIMUM=3.5

export CMAKE_OSX_DEPLOYMENT_TARGET="${MACOSX_DEPLOYMENT_TARGET}"
export CMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}
export CMAKE_CXX_COMPILER_LAUNCHER=ccache
# disable gcc 10 pstl TBB backend as it uses the old TBB API
export CMAKE_CXX_FLAGS='"-fvisibility=hidden -D_GLIBCXX_USE_TBB_PAR_BACKEND=0 -DNDEBUG"'
export BUILD_SHARED_LIBS=OFF
export CMAKE_DISABLE_FIND_PACKAGE_MPI=ON
export DUNE_ENABLE_PYTHONBINDINGS=OFF
export DUNE_PDELAB_ENABLE_TRACING=OFF
export DUNE_COPASI_DISABLE_FETCH_PACKAGE_ExprTk=ON
export CMAKE_DISABLE_FIND_PACKAGE_parafields=ON
export DUNE_COPASI_DISABLE_FETCH_PACKAGE_parafields=ON
# build dune-copasi with 2d and 3d support
export DUNE_COPASI_GRID_DIMENSIONS='"2;3"'
if [[ $MSYSTEM ]]; then
    # on windows add flags to support large object files
    # https://stackoverflow.com/questions/16596876/object-file-has-too-many-sections
    export CMAKE_CXX_FLAGS='"-fvisibility=hidden -Wa,-mbig-obj -D_GLIBCXX_USE_TBB_PAR_BACKEND=0 -DNDEBUG"'
fi
