.TH man 1 "02 August 2023" "2.0" "dune-copasi man page"
.SH NAME
dune-copasi \- Diffusion-Reaction numerical simulator
.SH SYNOPSIS
dune-copasi [OPTIONS]
.SH DESCRIPTION
dune-copasi is a numerical simulator for diffusion-reaction systems on single or multiple compartments.
.SH BUGS
https://gitlab.dune-project.org/copasi/dune-copasi/-/issues
.SH AUTHOR
Santiago Ospina De Los Rios (santiago.ospina@iwr.uni-heidelberg.de)
