#!/usr/bin/env python3

import sys
import warnings

from dune.copasi.cli.parser import get_parser

if __name__ == "__main__": # parse command line and call command handler
    try:
        with warnings.catch_warnings(record=True) as warn:
            try:
                parser = get_parser()
                args = parser.parse_args()
            except SystemExit:
                sys.exit(1)
            args.func(vars(args))
    except Exception as e:
        print("dune-copasi failed with ({0}) warning(s) and ({1}) error(s)".format(len(warn),1))
        raise
